Add Arbitrum One and Arbitrum Nova Support (#1112)
* add arbitrum one and arbitrum nova support

* fix archive parent chain ports

* fix exec script config

* update nitro-node version

diff --git a/build/docker/deb/Dockerfile b/build/docker/deb/Dockerfile
--- a/build/docker/deb/Dockerfile
+++ b/build/docker/deb/Dockerfile
@@ -9,6 +9,16 @@ RUN apt-get update && \
     apt-get install -y devscripts debhelper make dh-exec zstd && \
     apt-get clean
 
+# install docker cli
+ARG DOCKER_VERSION
+
+RUN if [ -z "$DOCKER_VERSION" ]; then echo "DOCKER_VERSION is a required build arg" && exit 1; fi
+
+RUN wget -O docker.tgz "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" && \
+    tar -xzf docker.tgz --strip 1 -C /usr/local/bin/ && \
+    rm docker.tgz && \
+    docker --version
+
 ADD gpg-keys /tmp/gpg-keys
 RUN gpg --batch --import /tmp/gpg-keys/*
 
